[package]
name = "k2f_math"
version = "0.2.0"
edition = "2021"
description = "K2F native math layout"
license = "Apache-2.0"
repository = "https://github.com/suzheng/k2f"
homepage = "https://github.com/suzheng/k2f"
documentation = "https://docs.rs/k2f_math"
authors = ["K2F Contributors"]
keywords = ["k2f", "math", "layout"]
categories = ["text-processing"]

[dependencies]
k2f_core = { path = "../k2f_core", version = "0.2.0" }
k2f_text = { path = "../k2f_text", version = "0.2.0" }
