"""Type stubs for the k2f PyO3 extension (PEP 561)."""

from typing import Optional, Tuple

def system_prompt() -> str: ...
def official_templates() -> list[str]: ...
def resolve_template(template: str) -> str: ...
def copy_template(template: str, dest: str) -> None: ...
def generate_signing_key() -> Tuple[str, str, str]: ...
def sign(
    package_bytes: bytes,
    secret_hex: str,
    signed_by: Optional[str] = None,
    signed_at: Optional[int] = None,
) -> bytes: ...
def markdown_to_k2f(
    md: str,
    title: str = "Document",
    template: str = "report",
) -> bytes: ...
def k2f_to_markdown(package_bytes: bytes) -> str: ...
def _cli_main() -> None: ...

class Editor:
    @staticmethod
    def open_bytes(bytes: bytes) -> "Editor": ...
    @staticmethod
    def open_dir(path: str) -> "Editor": ...
    @staticmethod
    def open_template(template: str) -> "Editor": ...
    def outline(self) -> str: ...
    def diff(self) -> str: ...
    def get_node(self, id: str) -> str: ...
    def selection(self, id: str) -> str: ...
    def clipboard(self, id: str) -> str: ...
    def replace_text(self, id: str, text: str) -> None: ...
    def set_role(
        self,
        id: str,
        role: str,
        variant: Optional[str] = None,
    ) -> None: ...
    def insert_node(self, parent_id: str, index: int, node_json: str) -> None: ...
    def delete_node(self, id: str) -> None: ...
    def set_generated_by(self, id: str) -> None: ...
    def set_running_header(self, text: str) -> None: ...
    def set_running_footer(self, text: str) -> None: ...
    def search(self, query: str) -> list[str]: ...
    def suggest(self, id: str, text: str) -> None: ...
    def accept_suggestion(self, id: str) -> None: ...
    def reject_suggestion(self, id: str) -> None: ...
    def save_bytes(self) -> bytes: ...
    def save_dir(self, path: str) -> None: ...
    def validate_package(self) -> None: ...
    def save_with(self, expected_content_hash: Optional[str] = None) -> bytes: ...
    def export_pdf_bytes(self) -> bytes: ...
    def export_pdf_bytes_at(self, scale: float = 2.0) -> bytes: ...
